CREATE TABLE [dbo].[tblOwner] (
    [ownerID]          INT             IDENTITY (1, 1) NOT NULL,
    [registrationDate] DATE            NOT NULL,
    [pictureOwner1]    VARBINARY (MAX) NOT NULL,
    [firstName1]       NVARCHAR (50)   NOT NULL,
    [middleName1]      NVARCHAR (50)   NULL,
    [lastName1]        NVARCHAR (50)   NOT NULL,
    [number1]          NVARCHAR (50)   NOT NULL,
    [address1]         NVARCHAR (50)   NOT NULL,
    [complement1]      NVARCHAR (50)   NULL,
    [city1]            NVARCHAR (50)   NOT NULL,
    [province1]        NVARCHAR (50)   NOT NULL,
    [postalCode1]      NVARCHAR (50)   NOT NULL,
    [phoneNumber1]     INT             NOT NULL,
    [otherNumber1]     INT             NULL,
    [email1]           NVARCHAR (50)   NULL UNIQUE,
    [pictureOwner2]    VARBINARY (MAX) NULL,
    [firstName2]       NVARCHAR (50)   NULL,
    [middleName2]      NVARCHAR (50)   NULL,
    [lastName2]        NVARCHAR (50)   NULL,
    [number2]          NVARCHAR (50)   NULL UNIQUE,
    [address2]         NVARCHAR (50)   NULL,
    [complement2]      NVARCHAR (50)   NULL,
    [city2]            NVARCHAR (50)   NULL,
    [province]         NVARCHAR (50)   NULL,
    [postalCode2]      NVARCHAR (50)   NULL,
    [phoneNumber2]     INT             NULL,
    [otherNumber2]     INT             NULL,
    [email2]           NVARCHAR (50)   NULL,
    [observations]     TEXT            NULL,
    PRIMARY KEY CLUSTERED ([ownerID] ASC)
);

