CREATE TABLE [dbo].[tblOwner]
(
	[ownerID] INT NOT NULL PRIMARY KEY IDENTITY,
	[registrationDate] DATE NOT NULL,
    [pictureOwner1] VARBINARY(MAX) NOT NULL, 
    [firstName1] NVARCHAR(50) NOT NULL, 
    [middleName1] NVARCHAR(50) NULL, 
    [lastName1] NVARCHAR(50) NOT NULL, 
    [number1] NVARCHAR(50) NOT NULL, 
    [address1] NVARCHAR(50) NOT NULL, 
    [complement1] NVARCHAR(50) NULL, 
    [city1] NVARCHAR(50) NOT NULL, 
    [provinceID1] INT NOT NULL, 
    [postalCode1] NVARCHAR(50) NOT NULL, 
    [phoneNumber1] NVARCHAR(50) NOT NULL, 
    [otherNumber1] NVARCHAR(50) NULL, 
    [email1] NVARCHAR(50) NULL,
    [pictureOwner2] VARBINARY(MAX) NULL, 
    [firstName2] NVARCHAR(50) NULL, 
    [middleName2] NVARCHAR(50) NULL, 
    [lastName2] NVARCHAR(50) NULL, 
    [number2] NVARCHAR(50) NULL, 
    [address2] NVARCHAR(50) NULL, 
    [complement2] NVARCHAR(50) NULL, 
    [city2] NVARCHAR(50) NULL, 
    [provinceID2] INT NULL, 
    [postalCode2] NVARCHAR(50) NULL, 
    [phoneNumber2] NVARCHAR(50) NULL, 
    [otherNumber2] NVARCHAR(50) NULL, 
    [email2] NVARCHAR(50) NULL, 
    [observations] TEXT NULL
)
